### ISSUE TITLE
Error while updating modules

### ISSUE THREAD

**Issue by BipinRathod** [luigisison/odoo-fhir#105]
2017-10-17 04:50:31,277 30164 INFO FHIR_DEV_28_sept openerp.tools.translate: loading /home/serpentcs/OpenERP/workspace/odoo_9/odoo_9/openerp/addons/base/i18n/en.po
2017-10-17 04:50:33,704 30164 INFO FHIR_DEV_28_sept openerp.addons.base.ir.ir_ui_view: Field `target_name` does not exist

Error context:
View `res.partner.form`
[view_id: 123, xml_id: base.view_partner_form, model: res.partner, parent_id: n/a]
2017-10-17 04:50:33,704 30164 ERROR FHIR_DEV_28_sept openerp.modules.registry: Failed to load registry
Traceback (most recent call last):
  File "/home/serpentcs/OpenERP/workspace/odoo_9/odoo_9/openerp/modules/registry.py", line 386, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/home/serpentcs/OpenERP/workspace/odoo_9/odoo_9/openerp/modules/loading.py", line 281, in load_modules
    loaded_modules, processed_modules = load_module_graph(cr, graph, status, perform_checks=update_module, report=report)
  File "/home/serpentcs/OpenERP/workspace/odoo_9/odoo_9/openerp/modules/loading.py", line 176, in load_module_graph
    registry['ir.ui.view']._validate_module_views(cr, SUPERUSER_ID, module_name)
  File "/home/serpentcs/OpenERP/workspace/odoo_9/odoo_9/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/serpentcs/OpenERP/workspace/odoo_9/odoo_9/openerp/addons/base/ir/ir_ui_view.py", line 1204, in _validate_module_views
    if not self._check_xml(cr, uid, [vid]):
  File "/home/serpentcs/OpenERP/workspace/odoo_9/odoo_9/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/serpentcs/OpenERP/workspace/odoo_9/odoo_9/openerp/addons/base/ir/ir_ui_view.py", line 305, in _check_xml
    self.postprocess_and_fields(cr, uid, view.model, view_doc, view.id, context=context)
  File "/home/serpentcs/OpenERP/workspace/odoo_9/odoo_9/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/serpentcs/OpenERP/workspace/odoo_9/odoo_9/openerp/addons/base/ir/ir_ui_view.py", line 933, in postprocess_and_fields
    self.raise_view_error(cr, user, message, view_id, context)
  File "/home/serpentcs/OpenERP/workspace/odoo_9/odoo_9/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/serpentcs/OpenERP/workspace/odoo_9/odoo_9/openerp/addons/base/ir/ir_ui_view.py", line 476, in raise_view_error
    raise AttributeError(message)
AttributeError: Field `target_name` does not exist

Error context:
View `res.partner.form`

**Comment by luigisison** [comment]
`target_name` was renamed to `link_name`.

Update DB.
