### ISSUE TITLE
KeyError: 'is_preferred'

### ISSUE THREAD

**Issue by luigisison** [luigisison/odoo-fhir#16]
Key Error occurs when compiling any model. For example, when compiling `hc_organization`, 

`is_preferred` is defined in model `hc.basic.association` found in `hc_base/models/hc_coding.py`

When `is_preferred` is removed (commented), there is a new Key Error `KeyError: 'use'`. `use` is defined in model `hc.contact.point.use` found in `hc_base/models/hc_telecom.py` and in model `hc.address.use` found in `hc_base/models/hc_address.py`.
```
2016-12-14 21:49:05,114 3723 [1;32m[1;49mINFO[0m FHIR-DEV openerp.modules.module: module hc_organization: creating or updating database tables
2016-12-14 21:49:06,509 3723 [1;32m[1;49mINFO[0m FHIR-DEV openerp.modules.loading: loading hc_organization/security/ir.model.access.csv
2016-12-14 21:49:11,655 3723 [1;32m[1;49mINFO[0m FHIR-DEV openerp.modules.loading: loading hc_organization/views/hc_res_organization_views.xml
2016-12-14 21:49:11,684 3723 [1;32m[1;49mINFO[0m FHIR-DEV openerp.modules.loading: loading hc_organization/views/hc_res_organization_templates.xml
2016-12-14 21:49:13,110 3723 [1;31m[1;49mERROR[0m FHIR-DEV openerp.modules.registry: Failed to load registry
Traceback (most recent call last):
  File "/odoo/odoo-server/openerp/modules/registry.py", line 386, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/odoo/odoo-server/openerp/modules/loading.py", line 334, in load_modules
    force, status, report, loaded_modules, update_module)
  File "/odoo/odoo-server/openerp/modules/loading.py", line 237, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/odoo/odoo-server/openerp/modules/loading.py", line 136, in load_module_graph
    registry.setup_models(cr, partial=True)
  File "/odoo/odoo-server/openerp/modules/registry.py", line 200, in setup_models
    model._setup_fields(cr, SUPERUSER_ID, partial)
  File "/odoo/odoo-server/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/odoo/odoo-server/openerp/api.py", line 354, in old_api
    result = method(recs, *args, **kwargs)
  File "/odoo/odoo-server/openerp/models.py", line 3052, in _setup_fields
    field.setup_full(self)
  File "/odoo/odoo-server/openerp/fields.py", line 498, in setup_full
    self._setup_related_full(model)
  File "/odoo/odoo-server/openerp/fields.py", line 535, in _setup_related_full
    field = target._fields[name]
KeyError: 'is_preferred'
```

**Comment by nandan-drc** [comment]
@luigisison please comment the field `address_id` from file `/addons/hc_related_person/models/hc_res_related_person.py` and class `RelatedPersonAddress`.
I did not get enough time to look into cause of that but this is the quick fix to make it work temporarily.

**Comment by luigisison** [comment]
Solution works! Error caused by inconsistent definition of `address_id` and class `RelatedPersonAddress`. How did you find the inconsistency?

**Comment by nandan-drc** [comment]
@luigisison it was showing an error in `/odoo/odoo-server/openerp/fields.py` so I debug there using the same techniques I used earlier by checking values there and I found issue in `address_id` field.

**Comment by luigisison** [comment]
Please describe the technique used to check values and find the issue.

**Comment by luigisison** [comment]
Technique to find the issue:

- Insert line 534 in `fields.py`
```print "Model", model```
