### ISSUE TITLE
1 How to Install Odoo in AWS

### ISSUE THREAD

**Issue by luigisison** [luigisison/odoo-fhir#78]

**Comment by luigisison** [comment]
Done:
* Installed AWS instance
* Installed Odoo 9c using [script](https://github.com/luigisison/moxylus/blob/master/Odoo9Community/install-odoo9c.sh)
* Installed Git
* Installed FHIR directory 

Pending
* Create database FHIR-DEV
* View Odoo in browser

**Comment by luigisison** [comment]
Created database FHIR-DEV
use the system user postgres to create your database
```
sudo -u postgres -i
createdb FHIR-DEV
exit
```

Create role "ubuntu"
`sudo su - postgres -c "createuser -s ubuntu" 2> /dev/null || true`

**Comment by luigisison** [comment]
```
ubuntu@ip-172-31-13-232:/odoo/odoo-server$ ./odoo.py
2017-08-09 01:20:07,346 9354 INFO ? openerp: OpenERP version 9.0c
2017-08-09 01:20:07,347 9354 INFO ? openerp: addons paths: ['/home/ubuntu/.local/share/Odoo/addons/9.0', u'/odoo/odoo-server/openerp/addons', u'/odoo/odoo-server/addons']
2017-08-09 01:20:07,347 9354 INFO ? openerp: database: default@default:default
2017-08-09 01:20:07,433 9354 INFO ? openerp.service.server: HTTP service (werkzeug) running on 0.0.0.0:8069
Exception in thread openerp.service.httpd:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/odoo/odoo-server/openerp/service/server.py", line 250, in http_thread
    self.httpd = ThreadedWSGIServerReloadable(self.interface, self.port, app)
  File "/odoo/odoo-server/openerp/service/server.py", line 105, in __init__
    handler=RequestHandler)
  File "/usr/lib/python2.7/dist-packages/werkzeug/serving.py", line 440, in __init__
    HTTPServer.__init__(self, (host, int(port)), handler)
  File "/usr/lib/python2.7/SocketServer.py", line 417, in __init__
    self.server_bind()
  File "/odoo/odoo-server/openerp/service/server.py", line 115, in server_bind
    super(ThreadedWSGIServerReloadable, self).server_bind()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 108, in server_bind
    SocketServer.TCPServer.server_bind(self)
  File "/usr/lib/python2.7/SocketServer.py", line 431, in server_bind
    self.socket.bind(self.server_address)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address already in use
```

**Comment by luigisison** [comment]
![image](https://user-images.githubusercontent.com/8397319/29101394-ca7306e0-7c66-11e7-9abc-0562f79a375c.png)

**Comment by luigisison** [comment]
killed existing processes
