### ISSUE TITLE
Issue in installing hc_base module

### ISSUE THREAD

**Issue by BipinRathod** [luigisison/odoo-fhir#86]
XMLSyntaxError: Double hyphen within comment: <!--         <record id="user_demo" model="res.users">, line 47, column 54
2017-08-23 04:50:22,508 339 ERROR health_care_23_aug openerp.http: Exception during JSON request handling.
Traceback (most recent call last):
  File "/home/serpentcs/OpenERP/workspace/odoo_9/odoo_9/openerp/http.py", line 650, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/serpentcs/OpenERP/workspace/odoo_9/odoo_9/openerp/http.py", line 687, in dispatch
    result = self._call_function(**self.params)
  File "/home/serpentcs/OpenERP/workspace/odoo_9/odoo_9/openerp/http.py", line 323, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/serpentcs/OpenERP/workspace/odoo_9/odoo_9/openerp/service/model.py", line 118, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/serpentcs/OpenERP/workspace/odoo_9/odoo_9/openerp/http.py", line 316, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/serpentcs/OpenERP/workspace/odoo_9/odoo_9/openerp/http.py", line 966, in __call__
    return self.method(*args, **kw)
  File "/home/serpentcs/OpenERP/workspace/odoo_9/odoo_9/openerp/http.py", line 516, in response_wrap
    response = f(*args, **kw)
  File "/home/serpentcs/OpenERP/workspace/odoo_9/odoo_9/addons/web/controllers/main.py", line 899, in call_button
    action = self._call_kw(model, method, args, {})
  File "/home/serpentcs/OpenERP/workspace/odoo_9/odoo_9/addons/web/controllers/main.py", line 887, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/home/serpentcs/OpenERP/workspace/odoo_9/odoo_9/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/serpentcs/OpenERP/workspace/odoo_9/odoo_9/openerp/addons/base/module/module.py", line 459, in button_immediate_install
    return self._button_immediate_function(cr, uid, ids, self.button_install, context=context)
  File "/home/serpentcs/OpenERP/workspace/odoo_9/odoo_9/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/serpentcs/OpenERP/workspace/odoo_9/odoo_9/openerp/addons/base/module/module.py", line 534, in _button_immediate_function
    registry = openerp.modules.registry.RegistryManager.new(cr.dbname, update_module=True)
  File "/home/serpentcs/OpenERP/workspace/odoo_9/odoo_9/openerp/modules/registry.py", line 386, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/home/serpentcs/OpenERP/workspace/odoo_9/odoo_9/openerp/modules/loading.py", line 340, in load_modules
    loaded_modules, update_module)
  File "/home/serpentcs/OpenERP/workspace/odoo_9/odoo_9/openerp/modules/loading.py", line 239, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/home/serpentcs/OpenERP/workspace/odoo_9/odoo_9/openerp/modules/loading.py", line 159, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='demo')
  File "/home/serpentcs/OpenERP/workspace/odoo_9/odoo_9/openerp/modules/loading.py", line 98, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/home/serpentcs/OpenERP/workspace/odoo_9/odoo_9/openerp/tools/convert.py", line 849, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/home/serpentcs/OpenERP/workspace/odoo_9/odoo_9/openerp/tools/convert.py", line 915, in convert_xml_import
    doc = etree.parse(xmlfile)
  File "lxml.etree.pyx", line 3239, in lxml.etree.parse (src/lxml/lxml.etree.c:69955)
  File "parser.pxi", line 1769, in lxml.etree._parseDocument (src/lxml/lxml.etree.c:102257)
  File "parser.pxi", line 1789, in lxml.etree._parseFilelikeDocument (src/lxml/lxml.etree.c:102516)
  File "parser.pxi", line 1684, in lxml.etree._parseDocFromFilelike (src/lxml/lxml.etree.c:101442)
  File "parser.pxi", line 1134, in lxml.etree._BaseParser._parseDocFromFilelike (src/lxml/lxml.etree.c:97069)
  File "parser.pxi", line 582, in lxml.etree._ParserContext._handleParseResultDoc (src/lxml/lxml.etree.c:91275)
  File "parser.pxi", line 683, in lxml.etree._handleParseResult (src/lxml/lxml.etree.c:92461)
  File "parser.pxi", line 622, in lxml.etree._raiseParseError (src/lxml/lxml.etree.c:91757)
XMLSyntaxError: Double hyphen within comment: <!--         <record id="user_demo" model="res.users">, line 47, column 54

**Comment by BipinRathod** [comment]
File "/home/serpentcs/OpenERP/workspace/odoo_9/odoo_9/openerp/modules/loading.py", line 98, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/home/serpentcs/OpenERP/workspace/odoo_9/odoo_9/openerp/tools/convert.py", line 849, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/home/serpentcs/OpenERP/workspace/odoo_9/odoo_9/openerp/tools/convert.py", line 932, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/home/serpentcs/OpenERP/workspace/odoo_9/odoo_9/openerp/tools/convert.py", line 799, in parse
    self.parse(rec, mode)
  File "/home/serpentcs/OpenERP/workspace/odoo_9/odoo_9/openerp/tools/convert.py", line 802, in parse
    self._tags[rec.tag](self.cr, rec, de, mode=mode)
  File "/home/serpentcs/OpenERP/workspace/odoo_9/odoo_9/openerp/tools/convert.py", line 697, in _tag_record
    f_val = self.id_get(cr, f_ref)
  File "/home/serpentcs/OpenERP/workspace/odoo_9/odoo_9/openerp/tools/convert.py", line 780, in id_get
    res = self.model_id_get(cr, id_str, raise_if_not_found)
  File "/home/serpentcs/OpenERP/workspace/odoo_9/odoo_9/openerp/tools/convert.py", line 791, in model_id_get
    raise_if_not_found=raise_if_not_found)
  File "/home/serpentcs/OpenERP/workspace/odoo_9/odoo_9/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/serpentcs/OpenERP/workspace/odoo_9/odoo_9/openerp/addons/base/ir/ir_model.py", line 1001, in xmlid_to_res_model_res_id
    return self.xmlid_lookup(cr, uid, xmlid)[1:3]
  File "/home/serpentcs/OpenERP/workspace/odoo_9/odoo_9/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "<string>", line 2, in xmlid_lookup
  File "/home/serpentcs/OpenERP/workspace/odoo_9/odoo_9/openerp/tools/cache.py", line 85, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/home/serpentcs/OpenERP/workspace/odoo_9/odoo_9/openerp/addons/base/ir/ir_model.py", line 991, in xmlid_lookup
    raise ValueError('External ID not found in the system: %s' % (xmlid))
ParseError: "External ID not found in the system: base.US" while parsing /home/serpentcs/OpenERP/workspace/Projects/odoo-fhir/addons/hc_base/demo/demo.xml:36, near
<record id="main_company" model="res.company">
            <field name="name">Fiore Healthcare</field>
            <field name="partner_id" ref="main_partner"/>
            <field name="rml_header1">Health and Wellness for All</field>
            <field name="currency_id" ref="base.US"/>
        </record>

**Comment by luigisison** [comment]
In `hc_base/demo/demo.xml`

Delete `<record id="user_demo"`

Update` main_partner` to `base.main_partner`

```
         <record id="base.main_company" model="res.company">
            <field name="name">Fiore Health</field>
            <field name="partner_id" ref="base.main_partner"/>
            <field name="rml_header1">Health and Wellness for All</field>
            <field name="currency_id" ref="base.US"/>
        </record>
```
