### ISSUE TITLE
Error : While installing hc_base module

### ISSUE THREAD

**Issue by BipinRathod** [luigisison/odoo-fhir#91]
Exception: Module loading hc_base failed: file hc_base/security/ir.model.access.csv could not be processed:
 Line 86 : No matching record found for external id 'model_hc_vs_fhir_all_type' in field 'Object'

**Comment by BipinRathod** [comment]
2017-09-19 04:36:56,631 1565 ERROR health_care_23_aug openerp.modules.registry: Failed to load registry
Traceback (most recent call last):
  File "/home/serpentcs/OpenERP/workspace/odoo_9/odoo_9/openerp/modules/registry.py", line 386, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/home/serpentcs/OpenERP/workspace/odoo_9/odoo_9/openerp/modules/loading.py", line 336, in load_modules
    force, status, report, loaded_modules, update_module)
  File "/home/serpentcs/OpenERP/workspace/odoo_9/odoo_9/openerp/modules/loading.py", line 239, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/home/serpentcs/OpenERP/workspace/odoo_9/odoo_9/openerp/modules/loading.py", line 156, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='data')
  File "/home/serpentcs/OpenERP/workspace/odoo_9/odoo_9/openerp/modules/loading.py", line 98, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/home/serpentcs/OpenERP/workspace/odoo_9/odoo_9/openerp/tools/convert.py", line 843, in convert_file
    convert_csv_import(cr, module, pathname, fp.read(), idref, mode, noupdate)
  File "/home/serpentcs/OpenERP/workspace/odoo_9/odoo_9/openerp/tools/convert.py", line 907, in convert_csv_import
    raise Exception(_('Module loading %s failed: file %s could not be processed:\n %s') % (module, fname, warning_msg))
Exception: Module loading hc_substance failed: file hc_substance/data/hc.vs.substance.code.csv could not be processed:
 Line 726 : No matching record found for external id 'subs_code_414053005' in field 'Children'
2017-09-19 04:36:56,631 1565 CRITICAL health_care_23_aug openerp.service.server: Failed to initialize database `health_care_23_aug`.
Traceback (most recent call last):
  File "/home/serpentcs/OpenERP/workspace/odoo_9/odoo_9/openerp/service/server.py", line 897, in preload_registries
    registry = RegistryManager.new(dbname, update_module=update_module)
  File "/home/serpentcs/OpenERP/workspace/odoo_9/odoo_9/openerp/modules/registry.py", line 386, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/home/serpentcs/OpenERP/workspace/odoo_9/odoo_9/openerp/modules/loading.py", line 336, in load_modules
    force, status, report, loaded_modules, update_module)
  File "/home/serpentcs/OpenERP/workspace/odoo_9/odoo_9/openerp/modules/loading.py", line 239, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/home/serpentcs/OpenERP/workspace/odoo_9/odoo_9/openerp/modules/loading.py", line 156, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='data')
  File "/home/serpentcs/OpenERP/workspace/odoo_9/odoo_9/openerp/modules/loading.py", line 98, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/home/serpentcs/OpenERP/workspace/odoo_9/odoo_9/openerp/tools/convert.py", line 843, in convert_file
    convert_csv_import(cr, module, pathname, fp.read(), idref, mode, noupdate)
  File "/home/serpentcs/OpenERP/workspace/odoo_9/odoo_9/openerp/tools/convert.py", line 907, in convert_csv_import
    raise Exception(_('Module loading %s failed: file %s could not be processed:\n %s') % (module, fname, warning_msg))
Exception: Module loading hc_substance failed: file hc_substance/data/hc.vs.substance.code.csv could not be processed:
 Line 726 : No matching record found for external id 'subs_code_414053005' in field 'Children'

**Comment by BipinRathod** [comment]
2017-09-19 10:51:46,659 18611 INFO health_care_18_sept openerp.modules.loading: loading hc_base/security/ir.model.access.csv
2017-09-19 10:51:47,790 18611 ERROR health_care_18_sept openerp.modules.registry: Failed to load registry
Traceback (most recent call last):
  File "/home/serpentcs/OpenERP/workspace/odoo_9/odoo_9/openerp/modules/registry.py", line 386, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/home/serpentcs/OpenERP/workspace/odoo_9/odoo_9/openerp/modules/loading.py", line 340, in load_modules
    loaded_modules, update_module)
  File "/home/serpentcs/OpenERP/workspace/odoo_9/odoo_9/openerp/modules/loading.py", line 239, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/home/serpentcs/OpenERP/workspace/odoo_9/odoo_9/openerp/modules/loading.py", line 156, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='data')
  File "/home/serpentcs/OpenERP/workspace/odoo_9/odoo_9/openerp/modules/loading.py", line 98, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/home/serpentcs/OpenERP/workspace/odoo_9/odoo_9/openerp/tools/convert.py", line 843, in convert_file
    convert_csv_import(cr, module, pathname, fp.read(), idref, mode, noupdate)
  File "/home/serpentcs/OpenERP/workspace/odoo_9/odoo_9/openerp/tools/convert.py", line 907, in convert_csv_import
    raise Exception(_('Module loading %s failed: file %s could not be processed:\n %s') % (module, fname, warning_msg))
Exception: Module loading hc_base failed: file hc_base/security/ir.model.access.csv could not be processed:
 Line 103 : No matching record found for external id 'model_hc_vs_value_code' in field 'Object'
2017-09-19 10:51:47,790 18611 ERROR health_care_18_sept openerp.http: Exception during JSON request handling.
Traceback (most recent call last):
  File "/home/serpentcs/OpenERP/workspace/odoo_9/odoo_9/openerp/http.py", line 650, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/serpentcs/OpenERP/workspace/odoo_9/odoo_9/openerp/http.py", line 687, in dispatch
    result = self._call_function(**self.params)
  File "/home/serpentcs/OpenERP/workspace/odoo_9/odoo_9/openerp/http.py", line 323, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/serpentcs/OpenERP/workspace/odoo_9/odoo_9/openerp/service/model.py", line 118, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/serpentcs/OpenERP/workspace/odoo_9/odoo_9/openerp/http.py", line 316, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/serpentcs/OpenERP/workspace/odoo_9/odoo_9/openerp/http.py", line 966, in __call__
    return self.method(*args, **kw)
  File "/home/serpentcs/OpenERP/workspace/odoo_9/odoo_9/openerp/http.py", line 516, in response_wrap
    response = f(*args, **kw)
  File "/home/serpentcs/OpenERP/workspace/odoo_9/odoo_9/addons/web/controllers/main.py", line 899, in call_button
    action = self._call_kw(model, method, args, {})
  File "/home/serpentcs/OpenERP/workspace/odoo_9/odoo_9/addons/web/controllers/main.py", line 887, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/home/serpentcs/OpenERP/workspace/odoo_9/odoo_9/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/serpentcs/OpenERP/workspace/odoo_9/odoo_9/openerp/addons/base/module/module.py", line 459, in button_immediate_install
    return self._button_immediate_function(cr, uid, ids, self.button_install, context=context)
  File "/home/serpentcs/OpenERP/workspace/odoo_9/odoo_9/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/serpentcs/OpenERP/workspace/odoo_9/odoo_9/openerp/addons/base/module/module.py", line 534, in _button_immediate_function
    registry = openerp.modules.registry.RegistryManager.new(cr.dbname, update_module=True)
  File "/home/serpentcs/OpenERP/workspace/odoo_9/odoo_9/openerp/modules/registry.py", line 386, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/home/serpentcs/OpenERP/workspace/odoo_9/odoo_9/openerp/modules/loading.py", line 340, in load_modules
    loaded_modules, update_module)
  File "/home/serpentcs/OpenERP/workspace/odoo_9/odoo_9/openerp/modules/loading.py", line 239, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/home/serpentcs/OpenERP/workspace/odoo_9/odoo_9/openerp/modules/loading.py", line 156, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='data')
  File "/home/serpentcs/OpenERP/workspace/odoo_9/odoo_9/openerp/modules/loading.py", line 98, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/home/serpentcs/OpenERP/workspace/odoo_9/odoo_9/openerp/tools/convert.py", line 843, in convert_file
    convert_csv_import(cr, module, pathname, fp.read(), idref, mode, noupdate)
  File "/home/serpentcs/OpenERP/workspace/odoo_9/odoo_9/openerp/tools/convert.py", line 907, in convert_csv_import
    raise Exception(_('Module loading %s failed: file %s could not be processed:\n %s') % (module, fname, warning_msg))
Exception: Module loading hc_base failed: file hc_base/security/ir.model.access.csv could not be processed:
 Line 103 : No matching record found for external id 'model_hc_vs_value_code' in field 'Object'

**Comment by luigisison** [comment]
Fix: `hc.vs.fhir.all.type` defined in `hc_base/hc_value_set_contains.py`

Fix: `model_hc_vs_value_code` defined in `hc_base_metadata_type/security/ir.model.access.csv`

`hc_substance/data/hc.vs.substance.code.csv` Child record `subs_code_414053005` is Line 785 which is after the Parent record in Line 726. No change made. Reload the file and report exception if any.

**Comment by BipinRathod** [comment]
2017-09-19 13:45:14,430 26859 INFO health_care_18_sept openerp.modules.loading: loading hc_base/demo/demo.xml
2017-09-19 13:45:14,627 26859 WARNING health_care_18_sept openerp.models: res.partner.write() with unknown fields: company_name
2017-09-19 13:45:14,724 26859 ERROR health_care_18_sept openerp.modules.registry: Failed to load registry
Traceback (most recent call last):
  File "/home/serpentcs/OpenERP/workspace/odoo_9/odoo_9/openerp/modules/registry.py", line 386, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/home/serpentcs/OpenERP/workspace/odoo_9/odoo_9/openerp/modules/loading.py", line 340, in load_modules
    loaded_modules, update_module)
  File "/home/serpentcs/OpenERP/workspace/odoo_9/odoo_9/openerp/modules/loading.py", line 239, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/home/serpentcs/OpenERP/workspace/odoo_9/odoo_9/openerp/modules/loading.py", line 159, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='demo')
  File "/home/serpentcs/OpenERP/workspace/odoo_9/odoo_9/openerp/modules/loading.py", line 98, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/home/serpentcs/OpenERP/workspace/odoo_9/odoo_9/openerp/tools/convert.py", line 849, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/home/serpentcs/OpenERP/workspace/odoo_9/odoo_9/openerp/tools/convert.py", line 932, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/home/serpentcs/OpenERP/workspace/odoo_9/odoo_9/openerp/tools/convert.py", line 799, in parse
    self.parse(rec, mode)
  File "/home/serpentcs/OpenERP/workspace/odoo_9/odoo_9/openerp/tools/convert.py", line 802, in parse
    self._tags[rec.tag](self.cr, rec, de, mode=mode)
  File "/home/serpentcs/OpenERP/workspace/odoo_9/odoo_9/openerp/tools/convert.py", line 697, in _tag_record
    f_val = self.id_get(cr, f_ref)
  File "/home/serpentcs/OpenERP/workspace/odoo_9/odoo_9/openerp/tools/convert.py", line 780, in id_get
    res = self.model_id_get(cr, id_str, raise_if_not_found)
  File "/home/serpentcs/OpenERP/workspace/odoo_9/odoo_9/openerp/tools/convert.py", line 791, in model_id_get
    raise_if_not_found=raise_if_not_found)
  File "/home/serpentcs/OpenERP/workspace/odoo_9/odoo_9/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/serpentcs/OpenERP/workspace/odoo_9/odoo_9/openerp/addons/base/ir/ir_model.py", line 1001, in xmlid_to_res_model_res_id
    return self.xmlid_lookup(cr, uid, xmlid)[1:3]
  File "/home/serpentcs/OpenERP/workspace/odoo_9/odoo_9/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "<string>", line 2, in xmlid_lookup
  File "/home/serpentcs/OpenERP/workspace/odoo_9/odoo_9/openerp/tools/cache.py", line 85, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/home/serpentcs/OpenERP/workspace/odoo_9/odoo_9/openerp/addons/base/ir/ir_model.py", line 991, in xmlid_lookup
    raise ValueError('External ID not found in the system: %s' % (xmlid))
ParseError: "External ID not found in the system: base.US" while parsing /home/serpentcs/OpenERP/workspace/Projects/odoo-fhir/addons/hc_base/demo/demo.xml:36, near
<record id="base.main_company" model="res.company">
            <field name="name">Fiore Health</field>
            <field name="partner_id" ref="base.main_partner"/>
            <field name="rml_header1">Health and Wellness for All</field>
            <field name="currency_id" ref="base.US"/>
        </record>
2017-09-19 13:45:14,787 26859 ERROR health_care_18_sept openerp.http: Exception during JSON request handling.
Traceback (most recent call last):
  File "/home/serpentcs/OpenERP/workspace/odoo_9/odoo_9/openerp/http.py", line 650, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/serpentcs/OpenERP/workspace/odoo_9/odoo_9/openerp/http.py", line 687, in dispatch
    result = self._call_function(**self.params)
  File "/home/serpentcs/OpenERP/workspace/odoo_9/odoo_9/openerp/http.py", line 323, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/serpentcs/OpenERP/workspace/odoo_9/odoo_9/openerp/service/model.py", line 118, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/serpentcs/OpenERP/workspace/odoo_9/odoo_9/openerp/http.py", line 316, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/serpentcs/OpenERP/workspace/odoo_9/odoo_9/openerp/http.py", line 966, in __call__
    return self.method(*args, **kw)
  File "/home/serpentcs/OpenERP/workspace/odoo_9/odoo_9/openerp/http.py", line 516, in response_wrap
    response = f(*args, **kw)
  File "/home/serpentcs/OpenERP/workspace/odoo_9/odoo_9/addons/web/controllers/main.py", line 899, in call_button
    action = self._call_kw(model, method, args, {})
  File "/home/serpentcs/OpenERP/workspace/odoo_9/odoo_9/addons/web/controllers/main.py", line 887, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/home/serpentcs/OpenERP/workspace/odoo_9/odoo_9/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/serpentcs/OpenERP/workspace/odoo_9/odoo_9/openerp/addons/base/module/module.py", line 459, in button_immediate_install
    return self._button_immediate_function(cr, uid, ids, self.button_install, context=context)
  File "/home/serpentcs/OpenERP/workspace/odoo_9/odoo_9/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/serpentcs/OpenERP/workspace/odoo_9/odoo_9/openerp/addons/base/module/module.py", line 534, in _button_immediate_function
    registry = openerp.modules.registry.RegistryManager.new(cr.dbname, update_module=True)
  File "/home/serpentcs/OpenERP/workspace/odoo_9/odoo_9/openerp/modules/registry.py", line 386, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/home/serpentcs/OpenERP/workspace/odoo_9/odoo_9/openerp/modules/loading.py", line 340, in load_modules
    loaded_modules, update_module)
  File "/home/serpentcs/OpenERP/workspace/odoo_9/odoo_9/openerp/modules/loading.py", line 239, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/home/serpentcs/OpenERP/workspace/odoo_9/odoo_9/openerp/modules/loading.py", line 159, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='demo')
  File "/home/serpentcs/OpenERP/workspace/odoo_9/odoo_9/openerp/modules/loading.py", line 98, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/home/serpentcs/OpenERP/workspace/odoo_9/odoo_9/openerp/tools/convert.py", line 849, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/home/serpentcs/OpenERP/workspace/odoo_9/odoo_9/openerp/tools/convert.py", line 932, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/home/serpentcs/OpenERP/workspace/odoo_9/odoo_9/openerp/tools/convert.py", line 799, in parse
    self.parse(rec, mode)
  File "/home/serpentcs/OpenERP/workspace/odoo_9/odoo_9/openerp/tools/convert.py", line 802, in parse
    self._tags[rec.tag](self.cr, rec, de, mode=mode)
  File "/home/serpentcs/OpenERP/workspace/odoo_9/odoo_9/openerp/tools/convert.py", line 697, in _tag_record
    f_val = self.id_get(cr, f_ref)
  File "/home/serpentcs/OpenERP/workspace/odoo_9/odoo_9/openerp/tools/convert.py", line 780, in id_get
    res = self.model_id_get(cr, id_str, raise_if_not_found)
  File "/home/serpentcs/OpenERP/workspace/odoo_9/odoo_9/openerp/tools/convert.py", line 791, in model_id_get
    raise_if_not_found=raise_if_not_found)
  File "/home/serpentcs/OpenERP/workspace/odoo_9/odoo_9/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/serpentcs/OpenERP/workspace/odoo_9/odoo_9/openerp/addons/base/ir/ir_model.py", line 1001, in xmlid_to_res_model_res_id
    return self.xmlid_lookup(cr, uid, xmlid)[1:3]
  File "/home/serpentcs/OpenERP/workspace/odoo_9/odoo_9/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "<string>", line 2, in xmlid_lookup
  File "/home/serpentcs/OpenERP/workspace/odoo_9/odoo_9/openerp/tools/cache.py", line 85, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/home/serpentcs/OpenERP/workspace/odoo_9/odoo_9/openerp/addons/base/ir/ir_model.py", line 991, in xmlid_lookup
    raise ValueError('External ID not found in the system: %s' % (xmlid))
ParseError: "External ID not found in the system: base.US" while parsing /home/serpentcs/OpenERP/workspace/Projects/odoo-fhir/addons/hc_base/demo/demo.xml:36, near
<record id="base.main_company" model="res.company">
            <field name="name">Fiore Health</field>
            <field name="partner_id" ref="base.main_partner"/>
            <field name="rml_header1">Health and Wellness for All</field>
            <field name="currency_id" ref="base.US"/>
        </record>

**Comment by luigisison** [comment]
Record derived from `odoo/odoo/addons/base/base_data.xml`
```
        <record id="main_company" model="res.company">
            <field name="name">My Company</field>
            <field name="partner_id" ref="main_partner"/>
            <field name="rml_header1">My Company Tagline</field>
            <field name="currency_id" ref="base.EUR"/>
        </record>
```

Creates company record
![image](https://user-images.githubusercontent.com/8397319/30596425-e43b86a2-9d08-11e7-8ce7-193d4bbfdbf8.png)

**Comment by BipinRathod** [comment]
Installing hc_allergy_intolerance raised an error
=================================

Traceback (most recent call last):
  File "/home/serpentcs/OpenERP/workspace/odoo_9/odoo_9/openerp/http.py", line 650, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/serpentcs/OpenERP/workspace/odoo_9/odoo_9/openerp/http.py", line 687, in dispatch
    result = self._call_function(**self.params)
  File "/home/serpentcs/OpenERP/workspace/odoo_9/odoo_9/openerp/http.py", line 323, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/serpentcs/OpenERP/workspace/odoo_9/odoo_9/openerp/service/model.py", line 118, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/serpentcs/OpenERP/workspace/odoo_9/odoo_9/openerp/http.py", line 316, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/serpentcs/OpenERP/workspace/odoo_9/odoo_9/openerp/http.py", line 966, in __call__
    return self.method(*args, **kw)
  File "/home/serpentcs/OpenERP/workspace/odoo_9/odoo_9/openerp/http.py", line 516, in response_wrap
    response = f(*args, **kw)
  File "/home/serpentcs/OpenERP/workspace/odoo_9/odoo_9/addons/web/controllers/main.py", line 899, in call_button
    action = self._call_kw(model, method, args, {})
  File "/home/serpentcs/OpenERP/workspace/odoo_9/odoo_9/addons/web/controllers/main.py", line 887, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/home/serpentcs/OpenERP/workspace/odoo_9/odoo_9/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/serpentcs/OpenERP/workspace/odoo_9/odoo_9/openerp/addons/base/module/module.py", line 459, in button_immediate_install
    return self._button_immediate_function(cr, uid, ids, self.button_install, context=context)
  File "/home/serpentcs/OpenERP/workspace/odoo_9/odoo_9/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/serpentcs/OpenERP/workspace/odoo_9/odoo_9/openerp/addons/base/module/module.py", line 534, in _button_immediate_function
    registry = openerp.modules.registry.RegistryManager.new(cr.dbname, update_module=True)
  File "/home/serpentcs/OpenERP/workspace/odoo_9/odoo_9/openerp/modules/registry.py", line 386, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/home/serpentcs/OpenERP/workspace/odoo_9/odoo_9/openerp/modules/loading.py", line 340, in load_modules
    loaded_modules, update_module)
  File "/home/serpentcs/OpenERP/workspace/odoo_9/odoo_9/openerp/modules/loading.py", line 239, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/home/serpentcs/OpenERP/workspace/odoo_9/odoo_9/openerp/modules/loading.py", line 156, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='data')
  File "/home/serpentcs/OpenERP/workspace/odoo_9/odoo_9/openerp/modules/loading.py", line 98, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/home/serpentcs/OpenERP/workspace/odoo_9/odoo_9/openerp/tools/convert.py", line 843, in convert_file
    convert_csv_import(cr, module, pathname, fp.read(), idref, mode, noupdate)
  File "/home/serpentcs/OpenERP/workspace/odoo_9/odoo_9/openerp/tools/convert.py", line 907, in convert_csv_import
    raise Exception(_('Module loading %s failed: file %s could not be processed:\n %s') % (module, fname, warning_msg))
Exception: Module loading hc_substance failed: file hc_substance/data/hc.vs.substance.code.csv could not be processed:
 Line 710 : No matching record found for external id 'subs_code_406455002' in field 'Children'
